# Generated by Django 4.1.5 on 2023-02-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produscto',
            new_name='Producto',
        ),
    ]
